python main.py \
  --synthetic_train_data_dir /Users/jamezhan/PycharmProjects/aster.pytorch/data/CVPR2016 \
  --test_data_dir /Users/jamezhan/PycharmProjects/aster.pytorch/data/CVPR2016/ \
  --batch_size 2 \
  --workers 0 \
  --height 64 \
  --width 256 \
  --voc_type ALLCASES_SYMBOLS \
  --arch ResNet_ASTER \
  --with_lstm \
  --logs_dir logs/baseline_aster \
  --real_logs_dir /Users/jamezhan/PycharmProjects/aster.pytorch/data/ \
  --max_len 100 \
  --STN_ON \
  --tps_inputsize 32 64 \
  --tps_outputsize 32 100 \
  --tps_margins 0.05 0.05 \
  --stn_activation none \
  --num_control_points 20 \